question_data = [
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "The main character in the 'Half-Life'; franchise is named Morgan Freeman.",
     "correct_answer": "False", "incorrect_answers": "True"},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "The first computer bug was formed by faulty wires.", "correct_answer": "False",
     "incorrect_answers": "True"},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "Arcade Fire's 'The Suburbs'; won the Album of the Year award in the 2011 Grammys.",
     "correct_answer": "True", "incorrect_answers": "False"},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "Coca-Cola's original colour was green.", "correct_answer": "False",
     "incorrect_answers": "True"},
    {"category": "Geography", "type": "boolean", "difficulty": "medium",
     "question": "There are no roads in or out of Juneau, Alaska.",
     "correct_answer": "True", "incorrect_answers": "False"},
    {"category": "History", "type": "boolean", "difficulty": "medium",
     "question": "In World War II, Hawker Typhoons served in the Pacific theater.",
     "correct_answer": "False", "incorrect_answers": "True"},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
     "correct_answer": "False", "incorrect_answers": "True"},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "It is automatically considered entrapment in the United States"
                 " if the police sell you illegal substances without revealing themselves.",
     "correct_answer": "False", "incorrect_answers": "True"},
    {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
     "question": "111,111,111 x 111,111,111 = 12,345,678,987,654,321", "correct_answer": "True",
     "incorrect_answers": "False"},
    {"category": "Sports", "type": "boolean", "difficulty": "medium",
     "question": "Tennis was once known as Racquetball.",
     "correct_answer": "False", "incorrect_answers": "True"},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
     "question": "The Xenomorph from the science fiction film 'Alien'; has acidic blood.",
     "correct_answer": "True", "incorrect_answers": "False"},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "In 'Team Fortress 2', the Bill's Hat is a reference to the game 'Dota 2'.",
     "correct_answer": "False", "incorrect_answers": "True"},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "The ultimate phrase used by Pharah from Overwatch is: 'Justice rains from above!'",
     "correct_answer": "True", "incorrect_answers": "False"},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "hard",
     "question": "The chemical element Lithium is named after the country of Lithuania.",
     "correct_answer": "False", "incorrect_answers": "True"},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
     "question": "The video game 'Fuel'; has an open world that is 5,560 square miles?",
     "correct_answer": "True", "incorrect_answers": "False"},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "A Boolean value of '0'; represents which of these words?",
     "correct_answer": "False", "incorrect_answers": "True"}
]
